name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    # ... other steps ...

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is an example; use the action/version suitable for your needs
      with:
        # heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "pill-films"
        heroku_email: "marie@prangishvili@gmail.com"
        env: 
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}